# Generated by Django 3.0.4 on 2020-03-23 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('phone_number', models.CharField(max_length=13, unique=True)),
                ('passport_number', models.CharField(max_length=8, unique=True)),
                ('identity_code', models.CharField(max_length=15, unique=True)),
                ('salary', models.FloatField()),
                ('birth_date', models.DateField()),
                ('residence_permit', models.TextField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Users')),
            ],
        ),
    ]
