# Generated by Django 3.0.4 on 2020-04-08 18:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('role_name', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('phone_number', models.CharField(max_length=13, unique=True)),
                ('passport_number', models.CharField(max_length=8, unique=True)),
                ('identity_code', models.CharField(max_length=15, unique=True)),
                ('salary', models.FloatField()),
                ('birth_date', models.DateField()),
                ('residence_permit', models.TextField(max_length=255)),
                ('password', models.CharField(max_length=88)),
                ('role', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='users.Role')),
                ('user_company', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
