language: python
python:
  - "3.7-dev"

install:
  - pip install -r requirements/test_requirements.txt
  - pip install -r requirements/requirements.txt

script:
  - flake8 .

ignore:
  - reports/migrations users/migrations accounts/migrations