# Generated by Django 3.0.4 on 2020-03-23 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_expence', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('receiver', models.CharField(max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16, unique=True)),
                ('is_debit', models.BooleanField()),
                ('CVV', models.IntegerField()),
                ('pincode', models.IntegerField()),
                ('expiration_date', models.DateField()),
                ('amount', models.FloatField()),
                ('credit_limit', models.FloatField()),
                ('deposit_amount', models.FloatField()),
                ('credit_percentage', models.FloatField()),
                ('deposit_percentage', models.FloatField()),
                ('credit_start_date', models.DateTimeField()),
                ('credit_end_date', models.DateTimeField()),
                ('deposit_start_date', models.DateTimeField()),
                ('deposit_end_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Users')),
            ],
        ),
    ]
