# Generated by Django 3.0.4 on 2020-04-08 18:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('number', models.CharField(max_length=16, unique=True)),
                ('is_debit', models.BooleanField(default=True)),
                ('CVV', models.IntegerField()),
                ('pincode', models.IntegerField()),
                ('expiration_date', models.DateField()),
                ('amount', models.FloatField(null=True)),
                ('credit_limit', models.FloatField(null=True)),
                ('deposit_amount', models.FloatField(null=True)),
                ('credit_percentage', models.FloatField(null=True)),
                ('deposit_percentage', models.FloatField(null=True)),
                ('credit_start_date', models.DateTimeField(null=True)),
                ('credit_end_date', models.DateTimeField(null=True)),
                ('deposit_start_date', models.DateTimeField(null=True)),
                ('deposit_end_date', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('type_of_expence', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('receiver', models.CharField(max_length=16)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('company_name', models.CharField(max_length=25, unique=True)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('amount', models.FloatField(null=True)),
                ('reg_location', models.CharField(max_length=25, null=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Account')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
