# Generated by Django 3.0.4 on 2020-04-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200408_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type_of_expence',
            field=models.CharField(choices=[('ON_PT', 'Online Payment'), ('PT', 'Payment'), ('TR_USR', 'Transaction to another user'), ('UT_PT', 'Utility payments')], default='PT', max_length=6),
        ),
    ]
